# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
# Site settings
title: Vera Sativa
description: > # this means to ignore newlines until "email:"
   Científica, ingeniera y profesora de datos. Entreno modelos, construyo pipelines y guio a profesionales que trabajan con datos.
email: a-mail@mail.mail
#blog logo
logo: "/assets/images/vs_logo.png"
float_logo: true # true, false (default)
kramdown:
  html_to_native: true
# blog cover
cover: "/assets/images/chilewic.jpg"

# name: 'Dirk Fabisch'
author: 'Vera Sativa'
author_image: "/assets/images/avatar.jpeg"
og_default_img: "/assets/images/avatar.jpeg"
timezone: Americas/Santiago
paginate:	10

url: "https://verasativa.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'
#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:


  - icon:	github
    url:	https://github.com/verasativa/
    desc:	Github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/verasativa/
    desc:	LinedIn
    share_url:
    share_title:
    share_link:

  - icon:    book
    url:    /data-science-cheat-book/
    desc:    Cheat Book
    share_url:
    share_title:
    share_link:

  - icon:    podcast
    url:    /STEM.queer/
    desc:    Podcast
    share_url:
    share_title:
    share_link:

  - icon:	graduation-cap
    url:	/taller-2020/
    desc:	Escuela
    share_url:
    share_title:
    share_link:
